theme = "hugo-theme-blueberry-detox"
baseURL = "https://blog.davisvaughan.com/"
languageCode = "en-us"
title = "Data Insights"

[params]

    disqusShortname = "datainsights"
    google_analytics = "UA-99003915-1"
    
    twitter_name = "dvaughan32"
    github = "DavisVaughan"